# Copyright (c) 2026 Hubble Network, Inc.
# SPDX-License-Identifier: Apache-2.0

# Reasonable SHELL configuration for this application
CONFIG_SHELL=y
CONFIG_SHELL_HISTORY=n
CONFIG_SHELL_CMDS_RESIZE=n
CONFIG_DATE_SHELL=n
CONFIG_DEVMEM_SHELL=n
CONFIG_KERNEL_SHELL=n
CONFIG_DEVICE_SHELL=n
CONFIG_SHELL_CMDS=n
CONFIG_SHELL_STATS=n
CONFIG_LOG=y

CONFIG_SHELL_THREAD_PRIORITY_OVERRIDE=y
CONFIG_SHELL_THREAD_PRIORITY=7

# Hubble Network
CONFIG_HUBBLE_SAT_NETWORK=y
CONFIG_HUBBLE_SAT_NETWORK_DTM_MODE=y
CONFIG_HUBBLE_NETWORK_SECURITY_ENFORCE_NONCE_CHECK=n

# Use device uptime as the counter source because we
# don't need time for DTM mode
CONFIG_HUBBLE_COUNTER_SOURCE_DEVICE_UPTIME=y
