# Set to true to add reviewers to pull requests
addReviewers: true

# We assign assignees out of here
addAssignees: false

# A list of reviewers to be added to pull requests
reviewers:
  - ceolin

numberOfReviewers: 0

