/*
 * Copyright (c) 2026 Hubble Network, Inc.
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#include "dmm/dmm_policy.h"
#include "dmm_priority_ble_custom.h"

/* BLE Activity */
typedef enum {
	DMM_BLE_CONN_INITIATING = 0x3E8,
	DMM_BLE_ACTIVE_CONNECTION = 0x7D0,
	DMM_BLE_ADVERTISING = 0xBB8,
	DMM_BLE_SCANNING = 0xFA0,
	DMM_BLE_PERIODIC_SCANNING = 0x1388,
	DMM_BLE_PERIODIC_ADVERTISING = 0x1770,
} DMMStackActivityBLE;

/* Custom Activity */
typedef enum {
	DMM_CUSTOM_ACTIVITY_1 = 0x0001,
	DMM_CUSTOM_ACTIVITY_2 = 0x0002,
	DMM_CUSTOM_ACTIVITY_3 = 0x0003,
	DMM_CUSTOM_ACTIVITY_4 = 0x0004,
	DMM_CUSTOM_ACTIVITY_5 = 0x0005,
	DMM_CUSTOM_ACTIVITY_6 = 0x0006,
} DMMStackActivityCustom;


/* Global Priority Table: BLE connection is lower than Custom
 * This is just a placeholder, because DMM requires GPT to be able
 * to use DMM features. We don't need it because we don't do
 * stack concurrency.
 */
StackActivity activityBLE_ble_low_custom_high[ACTIVITY_NUM_BLE * PRIORITY_NUM] = {
	DMM_GLOBAL_PRIORITY(DMM_BLE_ACTIVE_CONNECTION, DMM_StackPNormal, 70),
	DMM_GLOBAL_PRIORITY(DMM_BLE_ACTIVE_CONNECTION, DMM_StackPHigh, 170),
	DMM_GLOBAL_PRIORITY(DMM_BLE_ACTIVE_CONNECTION, DMM_StackPUrgent, 250),

	DMM_GLOBAL_PRIORITY(DMM_BLE_CONN_INITIATING, DMM_StackPNormal, 70),
	DMM_GLOBAL_PRIORITY(DMM_BLE_CONN_INITIATING, DMM_StackPHigh, 195),
	DMM_GLOBAL_PRIORITY(DMM_BLE_CONN_INITIATING, DMM_StackPUrgent, 220),

	DMM_GLOBAL_PRIORITY(DMM_BLE_ADVERTISING, DMM_StackPNormal, 60),
	DMM_GLOBAL_PRIORITY(DMM_BLE_ADVERTISING, DMM_StackPHigh, 160),
	DMM_GLOBAL_PRIORITY(DMM_BLE_ADVERTISING, DMM_StackPUrgent, 210),

	DMM_GLOBAL_PRIORITY(DMM_BLE_SCANNING, DMM_StackPNormal, 60),
	DMM_GLOBAL_PRIORITY(DMM_BLE_SCANNING, DMM_StackPHigh, 160),
	DMM_GLOBAL_PRIORITY(DMM_BLE_SCANNING, DMM_StackPUrgent, 210),

	DMM_GLOBAL_PRIORITY(DMM_BLE_PERIODIC_SCANNING, DMM_StackPNormal, 80),
	DMM_GLOBAL_PRIORITY(DMM_BLE_PERIODIC_SCANNING, DMM_StackPHigh, 180),
	DMM_GLOBAL_PRIORITY(DMM_BLE_PERIODIC_SCANNING, DMM_StackPUrgent, 240),

	DMM_GLOBAL_PRIORITY(DMM_BLE_PERIODIC_ADVERTISING, DMM_StackPNormal, 65),
	DMM_GLOBAL_PRIORITY(DMM_BLE_PERIODIC_ADVERTISING, DMM_StackPHigh, 165),
	DMM_GLOBAL_PRIORITY(DMM_BLE_PERIODIC_ADVERTISING, DMM_StackPUrgent, 215),
};


StackActivity activityCustom_ble_low_custom_high[ACTIVITY_NUM_CUSTOM * PRIORITY_NUM] = {
	DMM_GLOBAL_PRIORITY(DMM_CUSTOM_ACTIVITY_3, DMM_StackPNormal, 80),
	DMM_GLOBAL_PRIORITY(DMM_CUSTOM_ACTIVITY_3, DMM_StackPHigh, 180),
	DMM_GLOBAL_PRIORITY(DMM_CUSTOM_ACTIVITY_3, DMM_StackPUrgent, 240),

	DMM_GLOBAL_PRIORITY(DMM_CUSTOM_ACTIVITY_1, DMM_StackPNormal, 100),
	DMM_GLOBAL_PRIORITY(DMM_CUSTOM_ACTIVITY_1, DMM_StackPHigh, 195),
	DMM_GLOBAL_PRIORITY(DMM_CUSTOM_ACTIVITY_1, DMM_StackPUrgent, 230),

	DMM_GLOBAL_PRIORITY(DMM_CUSTOM_ACTIVITY_2, DMM_StackPNormal, 90),
	DMM_GLOBAL_PRIORITY(DMM_CUSTOM_ACTIVITY_2, DMM_StackPHigh, 190),
	DMM_GLOBAL_PRIORITY(DMM_CUSTOM_ACTIVITY_2, DMM_StackPUrgent, 240),

	DMM_GLOBAL_PRIORITY(DMM_CUSTOM_ACTIVITY_6, DMM_StackPNormal, 90),
	DMM_GLOBAL_PRIORITY(DMM_CUSTOM_ACTIVITY_6, DMM_StackPHigh, 190),
	DMM_GLOBAL_PRIORITY(DMM_CUSTOM_ACTIVITY_6, DMM_StackPUrgent, 240),

	DMM_GLOBAL_PRIORITY(DMM_CUSTOM_ACTIVITY_4, DMM_StackPNormal, 50),
	DMM_GLOBAL_PRIORITY(DMM_CUSTOM_ACTIVITY_4, DMM_StackPHigh, 190),
	DMM_GLOBAL_PRIORITY(DMM_CUSTOM_ACTIVITY_4, DMM_StackPUrgent, 215),

	DMM_GLOBAL_PRIORITY(DMM_CUSTOM_ACTIVITY_5, DMM_StackPNormal, 80),
	DMM_GLOBAL_PRIORITY(DMM_CUSTOM_ACTIVITY_5, DMM_StackPHigh, 80),
	DMM_GLOBAL_PRIORITY(DMM_CUSTOM_ACTIVITY_5, DMM_StackPUrgent, 80),
};

/* the order of stacks in policy table and global table must be the same */
GlobalTable globalPriorityTable_bleCustom[DMMPOLICY_NUM_STACKS] = {
	{
		.globalTableArray = activityBLE_ble_low_custom_high,
		.tableSize = (uint8_t)(ACTIVITY_NUM_BLE * PRIORITY_NUM),
		.stackRole = DMMPolicy_StackRole_BlePeripheral,
	},

	{
		.globalTableArray = activityCustom_ble_low_custom_high,
		.tableSize = (uint8_t)(ACTIVITY_NUM_CUSTOM * PRIORITY_NUM),
		.stackRole = DMMPolicy_StackRole_Custom1,
	},
};
