"""
Fetch orbital params from Hubble API.

Writes a C struct file for the orbital params to <prefix>/sat_params.c,
where <prefix> is an optional directory prefix (default: current directory).

Environment variables:
    HUBBLE_API_TOKEN  - (required) Bearer token for authenticating with the
                        Hubble satellite API.
"""

import argparse
import os
from pathlib import Path

import requests

API_BASE = "https://api.hubble.com/api/satellite"
TOKEN = os.environ["HUBBLE_API_TOKEN"]

SAT_PARAMS_RELPATH = Path("sat_params.c")

# Orbital params fields copied verbatim from the API response into the C struct.
ORBITAL_PARAMS_FIELDS = (
    "n0",
    "ndot",
    "raan0",
    "raandot",
    "aop0",
    "aopdot",
    "inclination",
    "eccentricity",
)

HEADERS = {"Authorization": f"Bearer {TOKEN}"}


def fetch_json(endpoint, **params):
    """GET an API endpoint and return the decoded JSON body."""
    resp = requests.get(f"{API_BASE}/{endpoint}", headers=HEADERS, params=params or None)
    resp.raise_for_status()
    return resp.json()


def iter_target_orbital_params(satellites):
    """Yield (sat_id, orbital_params) pairs for the satellites we care about."""
    for sat in satellites:
        sat_id = sat["satellite_id"]
        orbital_params = sat.get("orbital_params")
        if orbital_params:
            yield sat_id, orbital_params


def render_sat_params(orbital_params):
    """Render the sat_params.c source file as a string."""
    lines = [
        "/* This file is auto-generated by orbital_params_fetch.py.*/",
        "",
        "#include <hubble/sat/pass_prediction.h>",
        "",
        f"struct hubble_sat_orbital_params sats[{len(orbital_params)}] = {{",
    ]

    for sat_id, params in orbital_params:
        lines.append("    {")
        lines.append(f"        .t0 = {params['t0']},")
        lines.extend(f"        .{field} = {params[field]!r}," for field in ORBITAL_PARAMS_FIELDS)
        lines.append(f"        .satellite_id = {sat_id},")
        lines.append("    },")

    lines.append("};")
    return "\n".join(lines) + "\n"


def parse_args():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "prefix",
        nargs="?",
        default=Path(""),
        type=Path,
        help=f"Directory prefix prepended to the output file ({SAT_PARAMS_RELPATH}).",
    )
    return parser.parse_args()


def main():
    args = parse_args()
    output_path = args.prefix / SAT_PARAMS_RELPATH

    ephemeris = fetch_json("ephemeris")
    orbital_params = list(iter_target_orbital_params(ephemeris["satellites"]))

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(render_sat_params(orbital_params))
    print(f"Wrote {output_path} with information about {len(orbital_params)} satellites.")


if __name__ == "__main__":
    main()
